### ISSUE TITLE
mountlto can't find tape ready to mount

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/ltopers#207] opened 2019-09-28 18:53 UTC
We are starting to write LTO again for the first time in about 12 months.

Having some issues :)

```
/Users/medialab
≈:≈ formatlto -f
 Will force formatting.
1) 0
2) 32
Which LTO deck? 1
Enter the tape identifier: CHICAG
LTFS15000I Starting mkltfs, LTFS version 2.4.0.2, log level 2.
LTFS15041I Launched by "mkltfs -f -c --device=0 --tape-serial=CHICAG --volume-name=CHICAG".
LTFS15042I This binary is built for Mac OS X .
LTFS15043I GCC version is 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2).
LTFS17087I Kernel version: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64.
LTFS15003I Formatting device '0'.
LTFS15004I LTFS volume blocksize: 524288.
LTFS15005I Index partition placement policy: None.

LTFS11337I Update index-dirty flag (1) - CHICAG (0x0x7fab044050e0).
LTFS17085I Plugin: Loading "iokit" tape backend.
LTFS30810I Opening a device through iokit driver (0).
LTFS30814I Vendor ID is QUANTUM .
LTFS30815I Product ID is 'ULTRIUM-HH8     '.
LTFS30816I Firmware revision is J4D1.
LTFS30817I Drive serial is 1097001104.
LTFS17160I Maximum device block size is 1048576.
LTFS11330I Loading cartridge.
LTFS30854I Logical block protection is disabled.
LTFS11332I Load successful.
LTFS17157I Changing the drive setting to write-anywhere mode.
LTFS15049I Checking the medium (load).
LTFS30854I Logical block protection is disabled.
LTFS15010I Creating data partition b on SCSI partition 1.
LTFS15011I Creating index partition a on SCSI partition 0.
LTFS17165I Resetting the medium's capacity proportion.
LTFS11097I Partitioning the medium.
LTFS30865I MODESELECT returns Mode Parameters Rounded (-20101) 0.
LTFS11100I Writing label to partition a.
LTFS11100I Writing label to partition b.
LTFS11278I Writing index to partition b.
LTFS17235I Writing index of CHICAG to b (Reason: Format, 0 files) 1097001104.
LTFS17236I Wrote index of CHICAG (b, 1097001104).
LTFS11337I Update index-dirty flag (0) - CHICAG (0x0x7fab044050e0).
LTFS11278I Writing index to partition a.
LTFS17235I Writing index of CHICAG to a (Reason: Format, 0 files) 1097001104.
LTFS17236I Wrote index of CHICAG (a, 1097001104).
LTFS15013I Volume UUID is: fa445c8d-1838-4086-be14-3323afe8ed2e.

LTFS15019I Volume capacity is 11712 GB.
LTFS30854I Logical block protection is disabled.
LTFS15024I Medium formatted successfully.

/Users/medialab
≈:≈ mountlto
 Checking for ready tapes...
Checking for tape barcode.....
Checking for tape barcode.....
 Checked 2 decks and none appear to have tapes ready to mount.

/Users/medialab
≈:≈ ltfs -V
LTFS version 2.4.0.2.
LTFS Format Specification version 2.4.0.

/Users/medialab
≈:≈ ltfs -f -o devname=0
307 LTFS14000I LTFS starting, LTFS version 2.4.0.2, log level 2.
307 LTFS14058I LTFS Format Specification version 2.4.0.
307 LTFS14104I Launched by "ltfs -f -o devname=0".
307 LTFS14105I This binary is built for Mac OS X .
307 LTFS14106I GCC version is 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2).
307 LTFS17087I Kernel version: Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64.
307 LTFS14063I Sync type is "time", Sync time is 300 sec.
307 LTFS17085I Plugin: Loading "iokit" tape backend.
307 LTFS17085I Plugin: Loading "unified" iosched backend.
307 LTFS14095I Set the tape device write-anywhere mode to avoid cartridge ejection.
307 LTFS30810I Opening a device through iokit driver (0).
307 LTFS30814I Vendor ID is QUANTUM .
307 LTFS30815I Product ID is 'ULTRIUM-HH8     '.
307 LTFS30816I Firmware revision is J4D1.
307 LTFS30817I Drive serial is 1097001104.
307 LTFS17160I Maximum device block size is 1048576.
307 LTFS11330I Loading cartridge.
307 LTFS30854I Logical block protection is disabled.
307 LTFS11332I Load successful.
307 LTFS17157I Changing the drive setting to write-anywhere mode.
307 LTFS11005I Mounting the volume.
307 LTFS30854I Logical block protection is disabled.
307 LTFS30819W A length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523288).
307 LTFS30819W A length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523288).
307 LTFS12049E Cannot read: backend call failed (-21716).
307 LTFS17039E XML parser: failed to read a block from the medium (-21716).
Entity: line 1: parser error : Extra content at the end of the document

^
307 LTFS17037E XML parser: failed to read from XML stream.
307 LTFS17016E Cannot parse index direct from medium.
307 LTFS11194W Cannot read index: failed to read and parse XML data (-1014).
307 LTFS11024E Cannot mount volume: read index failed on the index partition.
307 LTFS14013E Cannot mount the volume.
307 LTFS30854I Logical block protection is disabled.
```

Our OSXFUSE version is 3.10.3

**Comment by NMAAHC** [comment] 2019-10-02 20:03
Maybe this is because we are using LTO8 tapes....?

**Comment by dericed** [comment] 2019-10-02 20:13
For that error message, the ibm documentation gives a really helpful recommendation: [call ibm](https://www.ibm.com/support/knowledgecenter/en/STQNYL_2.4.1/SDE_messages/LTFS30819W.html). Do you have an alternate tool for formatting LTO8 tape, like the LTFS Manager GUI? I'd be curious if an LTO8 tape formatted via something else would mount properly.

**Comment by NMAAHC** [comment] 2019-10-02 20:40
haha. yes, we saw that.

We haven't tried an alternate tool. Where do we find this LTFS Manager GUI? The Quantum one appears to only work for LTO 5 & 6

**Comment by dericed** [comment] 2019-10-02 20:42
Did you get any software with your drive?

**Comment by NMAAHC** [comment] 2019-10-02 20:45
ehhh...

**Comment by lawrenceaj** [comment] 2019-11-04 16:50
I was able to track down Quantum's LTFS Manager GUI and get it set up. However, we're still having the same issue. I can format a tape, but it won't mount. Would this indicate an issue with the computer we're using (Newest version of the Mac Mini) or possibly a hardware issue? 

I can send a log in a bit.

**Comment by lawrenceaj** [comment] 2019-11-04 17:38
Log comin' in hot, let me know if you want me to re-run it with verbose mode:

```
12:25:36.361 Version 1.1.6
12:25:36.362 Scanning for supported tape drives
12:31:32.011 Scanning for supported tape drives
12:31:32.020 Device 0: Found Device 0: QUANTUM  LTO8: 1097001104
12:32:30.999 Enabled verbose mode
12:32:32.385 Disabled verbose mode
12:32:41.483 Mount Volume
12:32:41.500 LTFS9015W Setting the locale to 'en_US.UTF-8'. If this is wrong, please set the LANG environment variable before starting ltfs.
12:32:41.502 307 LTFS14000I LTFS starting, LTFS version 2.4.0.2, log level 2.
12:32:41.502 307 LTFS14058I LTFS Format Specification version 2.4.0.
12:32:41.502 307 LTFS14104I Launched by "/usr/local/bin/ltfs /Users/medialab/Volumes/CHI001 -odevname=0 -ovolname=CHI001 -ovolicon=/Applications/Quantum LTFS Manager.app/Contents/Resources/quantum-ltfs.icns -o sync_type=time@5 -o eject -f".
12:32:41.503 307 LTFS14105I This binary is built for Mac OS X .
12:32:41.503 307 LTFS14106I GCC version is 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2).
12:32:41.503 307 LTFS17087I Kernel version: Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64.
12:32:41.503 307 LTFS14063I Sync type is "time", Sync time is 300 sec.
12:32:41.504 307 LTFS17085I Plugin: Loading "iokit" tape backend.
12:32:41.505 307 LTFS17085I Plugin: Loading "unified" iosched backend.
12:32:41.506 307 LTFS30810I Opening a device through iokit driver (0).
12:32:41.515 307 LTFS30814I Vendor ID is QUANTUM .
12:32:41.516 307 LTFS30815I Product ID is 'ULTRIUM-HH8     '.
12:32:41.516 307 LTFS30816I Firmware revision is J4D1.
12:32:41.516 307 LTFS30817I Drive serial is 1097001104.
12:32:41.519 307 LTFS17160I Maximum device block size is 1048576.
12:32:41.520 307 LTFS11330I Loading cartridge.
12:32:41.530 307 LTFS30854I Logical block protection is disabled.
12:32:41.536 307 LTFS11332I Load successful.
12:32:41.544 307 LTFS17157I Changing the drive setting to append-only mode.
12:32:41.551 307 LTFS11005I Mounting the volume.
12:32:41.562 307 LTFS30854I Logical block protection is disabled.
12:32:52.333 307 LTFS30819W A length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523288).
12:32:52.359 307 LTFS30819W A length mismatch is detected. (Act = 524288, resid = 0, resid_sense = 523288).
12:32:52.366 307 LTFS12049E Cannot read: backend call failed (-21716).
12:32:52.366 307 LTFS17039E XML parser: failed to read a block from the medium (-21716).
12:32:52.366 Entity: line 1: parser error : Extra content at the end of the document
12:32:52.367 
12:32:52.367 ^
12:32:52.367 307 LTFS17037E XML parser: failed to read from XML stream.
12:32:52.367 307 LTFS17016E Cannot parse index direct from medium.
12:32:52.367 307 LTFS11194W Cannot read index: failed to read and parse XML data (-1014).
12:32:52.368 307 LTFS11024E Cannot mount volume: read index failed on the index partition.
12:32:52.368 307 LTFS14013E Cannot mount the volume.
12:33:42.700 307 LTFS30854I Logical block protection is disabled.
12:33:42.704 /usr/local/bin/ltfs '/Users/medialab/Volumes/CHI001' -odevname=0 -ovolname='CHI001' -ovolicon='/Applications/Quantum LTFS Manager.app/Contents/Resources/quantum-ltfs.icns' -o sync_type=time@5   -o eject    -f 2>&1
12:33:42.704 ltfs exited with status 1
```

**Comment by matthew-mclaren** [comment] 2020-02-21 06:38
Hi, did you ever find a solution? Having the same problem running a Qualstar Q24 robot from a new Mac Mini with ATTO FC-82EN card.

**Comment by matthew-mclaren** [comment] 2020-02-21 16:58
Looks like setting the ATTO Maximum I/O Transfer Size to 1MB fixed the problem for us.

**Comment by retokromer** [comment] 2020-02-21 17:03
Thank you, @matthew-mclaren, for reporting! Do you use an ATTO card with a Mac mini?

**Comment by matthew-mclaren** [comment] 2020-02-21 17:18
@retokromer, yes, I have the Mac Mini in a TB3 Sonnet server chassis and have the ATTO card in there.

**Comment by retokromer** [comment] 2020-02-21 18:18
>in a TB3 Sonnet server chassis 

Ah, I understand. Thank you, @matthew-mclaren! (We work with Mac mini and external ATTO ThunderLink converters.)

**Comment by retokromer** [comment] 2020-02-23 08:59
I can confirm that using an IBM desk with their software I got the useless [“A length mismatch is detected.”](https://www.ibm.com/support/knowledgecenter/en/STQNYL_2.4.1/SDE_messages/LTFS30819W.html) error as well.

**Comment by lawrenceaj** [comment] 2020-02-25 18:10
We still haven't solved our issue. We're using a mac mini with a [High Point RocketStor 6661A-mSAS2](https://highpoint-tech.com/USA_new/series-rs6661a-msas2-overview.htm)

**Comment by dericed** [comment] 2020-02-25 19:05
@lawrenceaj, did you see the discussion at https://github.com/LinearTapeFileSystem/ltfs/issues/184.

**Comment by firedom** [comment] 2020-11-09 13:22
I also encountered this problem where the drive automatically initializes a new tape when it is inserted (In my drive: IBM LTO5), and if you interrupt the process, the tape can be irreversibly damaged, and never formatting successfully.
Terminal return error: Cannot reset the capacity proportion: backend call failed (-20603)

**Comment by Hloni-ux** [comment] 2021-02-24 17:46
@matthew-mclaren  how did you set the ATTO Maximum I/O Transfer Size to 1MB? I am getting the same error on Mac Pro 5.1, cant mount LTO 7 tapes all of a sudden.

**Comment by matthew-mclaren** [comment] 2021-03-03 18:36
@Hloni-ux , there is an option to set the Maximum I/O Transfer size in the Atto Config Tool on the "Advanced" tab.

**Comment by krim404** [comment] 2023-03-07 23:48
Two years have gone - any update on this topic?

**Comment by retokromer** [comment] 2023-03-08 06:39
ATTO ExpressSAS H680 works also under macOS.

**Comment by dericed** [comment] 2024-02-14 15:57
@BleakleyMcD The process of finding the tapes and mounting them was reworked. I'm going to close this, but please test and re-open if needed.

**Closed by dericed** 2024-02-14 15:57 UTC

**Comment by alexshnup** [comment] 2025-02-25 02:19
> Looks like setting the ATTO Maximum I/O Transfer Size to 1MB fixed the problem for us.

Thank you so much. It's really work for me.
